#!/bin/sh

set -o errexit
set -o nounset

startSection() {
    if [ "${CI:-}" = true ]; then
        echo "::group::$1"
    else
        startSection_length=${#1}
        printf "\n##%${startSection_length}s##\n" ' ' | tr ' ' '#'
        printf '# %s #\n' "$1"
        printf "##%${startSection_length}s##\n" ' ' | tr ' ' '#'
    fi
}
endSection() {
    if [ "${CI:-}" = true ]; then
        echo "::endgroup::"
    fi
}

startSection 'Configuring environment'
printf '(PHP version: %s, Composer version: %s)\n' "$CCM_PHP_VERSION" "$CCM_COMPOSER_VERSION"
switch-php "$CCM_PHP_VERSION"
switch-composer "$CCM_COMPOSER_VERSION"
cd /app
ccm-service start db
endSection

startSection 'Downloading and extracting ConcreteCMS'
printf '(URL: %s)\n' "$CCM_C5_ARCHIVE"
if test "$CCM_C5_ARCHIVE" != "${CCM_C5_ARCHIVE#https://github.com/}" || test "$CCM_C5_ARCHIVE" != "${CCM_C5_ARCHIVE#https://codeload.github.com/}"; then
    curl -sSL "$CCM_C5_ARCHIVE" | sudo -u www-data -- tar xz --strip 1
else
    curl -sSL -o /tmp/c5.zip "$CCM_C5_ARCHIVE"
    sudo -u www-data -- mkdir /tmp/c5
    sudo -u www-data -- unzip -q /tmp/c5.zip -d /tmp/c5
    mv /tmp/c5/*/** /app
    rm -rf /tmp/c5.zip /tmp/c5
    chmod +x concrete/bin/concrete5
fi
endSection

if ! test -d concrete/vendor; then
    startSection 'Installing composer dependencies'
    if test -f concrete/composer.json; then
        sed -i 's/"hautelook\/phpass"/"ozh\/phpass"/' concrete/composer.json
    fi
    if test -f composer.lock; then
        sed -i 's_\bhautelook/phpass\b_ozh/phpass_' composer.lock
    fi
    sudo -H -u www-data -- composer install --optimize-autoloader --no-cache
    endSection
fi

if [ "${CCM_PATCH_ENVIRONMENT_ONLY:-}" = Y ]; then
    startSection 'Patching Concrete for C5_ENVIRONMENT_ONLY support'
    sed -Ei 's/^return \$app;//' /app/application/bootstrap/start.php
    cat /tmp/start-patch >>/app/application/bootstrap/start.php
    cat /tmp/app-patch >>/app/application/bootstrap/app.php
    endSection
fi
rm -f /tmp/start-patch /tmp/app-patch

startSection 'Configuring PHPUnit'
printf '(PHPUnit version: %s)\n' "$CCM_PHPUNIT_VERSION"
if [ -f /app/concrete/vendor/phpunit/phpunit/phpunit ]; then
    update-alternatives --quiet --install /usr/local/bin/phpunit phpunit /app/concrete/vendor/phpunit/phpunit/phpunit 9999
fi
switch-phpunit "$CCM_PHPUNIT_VERSION"
endSection

startSection 'Installing Concrete'
c5 c5:install \
    --db-server=localhost \
    --db-username=c5 \
    --db-password=12345 \
    --db-database=c5 \
    --site='ConcreteCMS website' \
    --starting-point=$CCM_STARTING_POINT \
    --admin-email=admin@example.org \
    --admin-password=12345
endSection

startSection 'Confguring Concrete'
sudo -u www-data -- mkdir --mode=0755 -p /app/application/languages/site
c5 c5:config set -g concrete.seo.url_rewriting true
c5 c5:config set -g concrete.mail.method smtp
c5 c5:config set -g concrete.mail.methods.smtp.server 127.0.0.1
c5 c5:config set -g concrete.mail.methods.smtp.port 25
endSection

startSection 'Final operations'
c5 c5:clear-cache
ccm-service stop db
endSection

echo 'Ready.'
