#!/bin/sh

set -o errexit
set -o nounset

downloadRetries=10
downloadSleepFactor=20

startSection() {
    if [ "${CI:-}" = true ]; then
        echo "::group::$1"
    else
        startSection_length=${#1}
        printf "\n##%${startSection_length}s##\n" ' ' | tr ' ' '#'
        printf '# %s #\n' "$1"
        printf "##%${startSection_length}s##\n" ' ' | tr ' ' '#'
    fi
}
endSection() {
    if [ "${CI:-}" = true ]; then
        echo "::endgroup::"
    fi
}

downloadZip() {
    downloadZip_attempt=1
    while true; do
        downloadZip_tempFile=$(mktemp) || return 1
        if ! curl -sSLf -o "$downloadZip_tempFile" "$1"; then
            echo "Download attempt $downloadZip_attempt failed" >&2
        elif ! unzip -tq "$downloadZip_tempFile" >/dev/null 2>&1; then
            echo "ZIP validation attempt $downloadZip_attempt failed" >&2
        else
            printf '%s\n' "$downloadZip_tempFile"
            return 0
        fi
        rm -f "$downloadZip_tempFile"
        if [ $downloadZip_attempt -ge $downloadRetries ]; then
            echo "Download failed after $downloadZip_attempt attempts" >&2
            return 1
        fi
        
        printf "Sleeping for %s seconds and retrying...\n" $((downloadZip_attempt * downloadSleepFactor)) >&2
        sleep $((downloadZip_attempt * downloadSleepFactor))
        downloadZip_attempt=$((downloadZip_attempt + 1))
    done
}

downloadTGZ() {
    downloadTGZ_attempt=1
    while true; do
        downloadTGZ_tempFile=$(mktemp) || return 1
        if ! curl -sSLf -o "$downloadTGZ_tempFile" "$1"; then
            echo "Download attempt $downloadTGZ_attempt failed" >&2
        elif ! tar -tzf "$downloadTGZ_tempFile" >/dev/null 2>&1; then
            echo "TGZ validation attempt $downloadTGZ_attempt failed" >&2
        else
            printf '%s\n' "$downloadTGZ_tempFile"
            return 0
        fi
        rm -f "$downloadTGZ_tempFile"
        if [ $downloadTGZ_attempt -ge $downloadRetries ]; then
            echo "Download failed after $downloadTGZ_attempt attempts" >&2
            return 1
        fi
        printf "Sleeping for %s seconds and retrying...\n" $((downloadTGZ_attempt * downloadSleepFactor)) >&2
        sleep $((downloadTGZ_attempt * downloadSleepFactor))
        downloadTGZ_attempt=$((downloadTGZ_attempt + 1))
    done
}

startSection 'Configuring environment'
printf '(PHP version: %s, Composer version: %s)\n' "$CCM_PHP_VERSION" "$CCM_COMPOSER_VERSION"
switch-php "$CCM_PHP_VERSION"
switch-composer "$CCM_COMPOSER_VERSION"
cd /app
ccm-service start db
endSection

startSection 'Downloading and extracting ConcreteCMS'
printf '(URL: %s)\n' "$CCM_C5_ARCHIVE"
if test "$CCM_C5_ARCHIVE" != "${CCM_C5_ARCHIVE#https://github.com/}" || test "$CCM_C5_ARCHIVE" != "${CCM_C5_ARCHIVE#https://codeload.github.com/}"; then
    if ! tgzFile=$(downloadTGZ "$CCM_C5_ARCHIVE"); then
        echo "Failed to download and validate TGZ file from $CCM_C5_ARCHIVE" >&2
        exit 1
    fi
    chmod 0644 "$tgzFile"
    sudo -u www-data -- tar xzf "$tgzFile" --strip 1
    rm -f "$tgzFile"
else
    if ! zipFile=$(downloadZip "$CCM_C5_ARCHIVE"); then
        echo "Failed to download and validate ZIP file from $CCM_C5_ARCHIVE" >&2
        exit 1
    fi
    chmod 0644 "$zipFile"
    sudo -u www-data -- mkdir /tmp/c5
    sudo -u www-data -- unzip -q "$zipFile" -d /tmp/c5
    mv /tmp/c5/*/** /app
    rm -rf "$zipFile" /tmp/c5
    chmod +x concrete/bin/concrete5
fi
endSection

if ! test -d concrete/vendor; then
    startSection 'Installing composer dependencies'
    if test -f concrete/composer.json; then
        sed -i 's/"hautelook\/phpass"/"ozh\/phpass"/' concrete/composer.json
    fi
    if test -f composer.lock; then
        sed -i 's_\bhautelook/phpass\b_ozh/phpass_' composer.lock
    fi
    sudo -H -u www-data -- composer install --optimize-autoloader --no-cache
    endSection
fi

if [ "${CCM_PATCH_ENVIRONMENT_ONLY:-}" = Y ]; then
    startSection 'Patching Concrete for C5_ENVIRONMENT_ONLY support'
    sed -Ei 's/^return \$app;//' /app/application/bootstrap/start.php
    cat /tmp/start-patch >>/app/application/bootstrap/start.php
    cat /tmp/app-patch >>/app/application/bootstrap/app.php
    endSection
fi
rm -f /tmp/start-patch /tmp/app-patch

startSection 'Configuring PHPUnit'
printf '(PHPUnit version: %s)\n' "$CCM_PHPUNIT_VERSION"
if [ -f /app/concrete/vendor/phpunit/phpunit/phpunit ]; then
    update-alternatives --quiet --install /usr/local/bin/phpunit phpunit /app/concrete/vendor/phpunit/phpunit/phpunit 9999
fi
switch-phpunit "$CCM_PHPUNIT_VERSION"
endSection

startSection 'Installing Concrete'
c5 c5:install \
    --db-server=localhost \
    --db-username=c5 \
    --db-password=12345 \
    --db-database=c5 \
    --site='ConcreteCMS website' \
    --starting-point=$CCM_STARTING_POINT \
    --admin-email=admin@example.org \
    --admin-password=12345
endSection

startSection 'Confguring Concrete'
sudo -u www-data -- mkdir --mode=0755 -p /app/application/languages/site
echo 'application/languages/site created.'
c5 c5:config set -g concrete.seo.url_rewriting true
echo 'URL rewriting enabled.'
c5 c5:config set -g concrete.mail.method smtp
c5 c5:config set -g concrete.mail.methods.smtp.server 127.0.0.1
c5 c5:config set -g concrete.mail.methods.smtp.port 25
echo 'SMTP mail configured.'
if [ -f /app/.php-cs-fixer.dist.php ]; then
    echo 'php-cs-fixer configuration not installed because it already exists.'
elif [ -f /app/concrete/src/Support/CodingStyle/autoload.php ]; then
    cp /tmp/php-cs-fixer.config.php /app/.php-cs-fixer.dist.php
    chown www-data:www-data /app/.php-cs-fixer.dist.php
    echo 'php-cs-fixer configuration installed.'
else
    echo 'php-cs-fixer configuration not installed because not supported.'
fi
rm -f /tmp/php-cs-fixer.config.php
endSection

startSection 'Final operations'
c5 c5:clear-cache
ccm-service stop db
endSection

echo 'Ready.'
