#!/bin/sh

rc=0

printf 'Starting MariaDB... '
if mysqladmin status -s >/dev/null; then
    printf 'done.\n'
else
    /bin/sh -c '/usr/bin/mysqld_safe >/dev/null 2>&1 &'
    for i in $(seq 1 31); do
        if test $i -eq 31; then
            printf 'FAILED!.\n' >&2
            mysqladmin status
            rc=1
            break
        fi
        sleep 1
        if mysqladmin status -s >/dev/null; then
            printf 'done.\n'
            break
        fi
    done
fi

printf 'Starting nginx... '
if service nginx restart >/dev/null; then
    printf 'done.\n'
else
    printf 'FAILED!.\n' >&2
    rc=1
fi

printf 'Starting php-fpm... '
if test -f /run/php-fpm.pid; then
    printf 'done.\n'
else
    /bin/sh -c 'php-fpm >/var/log/php-fpm-log 2>&1 &'
    sleep 1
    if ! test -f /run/php-fpm.pid; then
        printf 'FAILED!.\n' >&2
        cat /var/log/php-fpm-log >&2
        rc=1
    else
        printf 'done.\n'
    fi
fi

exit $rc
