#!/bin/sh


rc=0

printf 'Stopping MariaDB... '
if mysqladmin status -s >/dev/null; then
    if mysqladmin shutdown; then
        printf 'done.\n'
    else
        printf 'FAILED!.\n' >&2
        rc=1
    fi
else
    printf 'done.\n'
fi

printf 'Stopping nginx... '
if service nginx stop; then
    printf 'done.\n'
else
    printf 'FAILED!.\n' >&2
    rc=1
fi

printf 'Stopping php-fpm... '
LSOF_OUT="$(lsof -iTCP:9000 2>&1 || true)"
if test -z "$LSOF_OUT"; then
    printf 'done.\n'
else
    IFS='
 ' LSOF_PID=$(printf %s "$LSOF_OUT" | awk 'NR > 1 {print $2}')
    if kill -s3 $LSOF_PID; then
        printf 'done.\n'
    else
        printf 'FAILED!.\n' >&2
        rc=1
    fi
fi

exit $rc
