#!/bin/sh

set -o errexit
set -o nounset

startSection() {
    if [ "${CI:-}" = true ]; then
        echo "::group::$1"
    else
        startSection_length=${#1}
        printf "\n##%${startSection_length}s##\n" ' ' | tr ' ' '#'
        printf '# %s #\n' "$1"
        printf "##%${startSection_length}s##\n" ' ' | tr ' ' '#'
    fi
}
endSection() {
    if [ "${CI:-}" = true ]; then
        echo "::endgroup::"
    fi
}

startSection 'Updating system'
apt-get update -qy
apt-get upgrade -qy
apt-get autoremove --purge -qy
endSection

startSection 'Installing apt packages'
echo 'tzdata tzdata/Areas select Etc' | debconf-set-selections
echo 'tzdata tzdata/Zones/Etc select UTC' | debconf-set-selections
apt-get install -qy --no-install-recommends apt-transport-https ca-certificates curl git gnupg2 patch software-properties-common sudo tzdata unzip
echo 'Set disable_coredump false' >> /etc/sudo.conf
endSection

startSection 'Configuring helper commands'
chmod 0755 \
    /usr/local/bin/c5 \
    /entrypoint.sh
endSection

startSection 'Installing PHP FPM'
LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
APT_PACKAGES=''
for PHP_VERSION in $PHP_VERSIONS; do
    APT_PACKAGES="$APT_PACKAGES php$PHP_VERSION-fpm"
    if [ -n "${PHP_EXTENSIONS_VSPECIFIC:-}" ]; then
        for PHP_EXTENSION in $PHP_EXTENSIONS_VSPECIFIC; do
            APT_PACKAGE="php$PHP_VERSION-$PHP_EXTENSION"
            case $APT_PACKAGE in
                php8.*-json)
                    ;;
                *)
                    APT_PACKAGES="$APT_PACKAGES $APT_PACKAGE"
                    ;;
            esac
        done
        unset PHP_EXTENSION
    fi
done
unset PHP_VERSION
if [ -n "${PHP_EXTENSIONS_COMMON:-}" ]; then
    APT_PACKAGES="$APT_PACKAGES $PHP_EXTENSIONS_COMMON"
fi
apt-get install -qy --no-install-recommends $APT_PACKAGES
unset APT_PACKAGES
endSection

startSection 'Installing NodeJS'
curl -sSL https://deb.nodesource.com/setup_18.x | bash -
apt-get install -qy --no-install-recommends nodejs
npm -g install grunt-cli
endSection

startSection 'Installing MariaDB'
# Broken - see https://jira.mariadb.org/browse/MDEV-37451
# curl -sSL https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --skip-maxscale --mariadb-server-version=mariadb-10.6
# Workaround - see https://mariadb.org/download/?t=repo-config&d=22.04+%22jammy%22&v=10.6
mkdir -p /etc/apt/keyrings
if [ ! -f /etc/apt/keyrings/mariadb-keyring.pgp ]; then
    curl -sSLf -o /etc/apt/keyrings/mariadb-keyring.pgp https://mariadb.org/mariadb_release_signing_key.pgp
fi
if ! [ -f /etc/apt/sources.list.d/mariadb.sources ]; then
    cat <<'EOT' >/etc/apt/sources.list.d/mariadb.sources
X-Repolib-Name: MariaDB
Types: deb
URIs: https://deb.mariadb.org/10.6/ubuntu
Suites: jammy
Components: main main/debug
Signed-By: /etc/apt/keyrings/mariadb-keyring.pgp
EOT
    apt-get update -qy
fi
apt-get install -qy --no-install-recommends mariadb-server
endSection

startSection 'Installing Nginx'
LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/nginx
apt-get install -qy --no-install-recommends nginx
endSection

startSection 'Installing Composer'
mkdir -p /var/www/.composer
chown -R www-data:www-data /var/www/.composer
curl -sSLf -o /tmp/composer-installer https://getcomposer.org/installer
php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer1 --1
update-alternatives --quiet --install /usr/local/bin/composer composer /usr/local/bin/composer1 10
php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer2.2 --2.2
update-alternatives --quiet --install /usr/local/bin/composer composer /usr/local/bin/composer2.2 20
php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer2 --2
update-alternatives --quiet --install /usr/local/bin/composer composer /usr/local/bin/composer2 29
rm /tmp/composer-installer
switch-composer 2.2
(sudo -H -u www-data -- composer clear-cache || true)
endSection

startSection 'Installing PHPUnit'
for v in $(seq 4 10); do
    echo "- PHPUnit $v"
    curl -sSLf -o /usr/local/bin/phpunit$v https://phar.phpunit.de/phpunit-$v.phar
    chmod +x /usr/local/bin/phpunit$v
    update-alternatives --quiet --install /usr/local/bin/phpunit phpunit /usr/local/bin/phpunit$v $v
done
switch-phpunit 8
endSection

startSection 'Configuring database'
sed -i -r 's/^(\s*bind-address\s*=\s*)127\.0\.0\.1(\s*)$/\10.0.0.0\2/' /etc/mysql/my.cnf
sed -i -r 's/^(\s*innodb_flush_method\s*=\s*)\S.*?(\s*)$/\1fsync\2/' /etc/mysql/my.cnf
(test -f /etc/mysql/mariadb.conf.d/50-server.cnf && sed -i -r 's/^(\s*bind-address\s*=\s*)127\.0\.0\.1(\s*)$/\10.0.0.0\2/' /etc/mysql/mariadb.conf.d/50-server.cnf || true)
(test -f /etc/mysql/mariadb.conf.d/50-server.cnf && echo 'innodb_flush_method = fsync' >> /etc/mysql/mariadb.conf.d/50-server.cnf || true)
ccm-service start db
echo "CREATE USER 'c5'@'%' IDENTIFIED BY '12345'; CREATE DATABASE c5 COLLATE 'utf8mb4_unicode_ci'; GRANT ALL PRIVILEGES ON c5.* TO 'c5'@'%'; FLUSH PRIVILEGES;" | mysql
endSection

startSection 'Final operations'
apt-get remove -qy --autoremove --purge software-properties-common
mkdir /app
chown www-data:www-data /app
ccm-service stop
apt-get clean -qy
rm -rf /var/lib/apt/lists/*
npm cache clean --force
rm -rf $HOME/.npm/_logs/*.log
truncate --size=0 /var/log/*.log /var/log/apt/*.log
rm -rf /var/log/apt/eipp.log.xz
endSection

echo 'Ready.'
