name: Build GitHub Pages

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - .github/workflows/build-pages.yml
      - data/matrix.json
      - gh-pages
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: gh-pages/package-lock.json
      -
        name: Install NPM packages
        working-directory: gh-pages
        run: npm ci
      -
        name: Build
        working-directory: gh-pages
        run: npm run-script build
      -
        name: Setup Pages
        uses: actions/configure-pages@v5
      -
        name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages/docker5
      -
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
