name: Update README

on:
  pull_request:
    paths:
      - .github/workflows/generate-matrix
      - .github/workflows/update-readme.yml
      - .github/workflows/generate-matrix
      - data/versions.json
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - .github/workflows/generate-matrix
      - .github/workflows/update-readme.yml
      - .github/workflows/update-readme
      - data/versions.json
  workflow_dispatch:
    inputs:
      publish:
        description: Publish
        type: boolean
        required: false

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      -
        name: Inspect environment
        id: inspect-environment
        run: |
          action=none
          case ${{ github.event_name }} in
            push)
              case "${{ github.event.head_commit.message }}" in
                \[skip\ ci\]*)
                  ;;
                *)
                  action=publish
                  ;;
              esac
              ;;
            pull_request)
              action=build
              ;;
            workflow_dispatch)
              action="${{ inputs.action}}"
              ;;
            workflow_dispatch)
              case '${{ inputs.publish }}' in
                t* | y* | 1)
                  action=publish
                  ;;
                *)
                  action=build
                  ;;
              esac
              ;;
          esac
          echo "action=$action" >> $GITHUB_OUTPUT
      -
        name: Print environment info
        run: |
          printf 'github.event_name: %s\n' "${{ github.event_name }}"
          printf 'github.ref: %s\n' "${{ github.ref }}"
          printf 'Action to be performed: %s\n' "${{ steps.inspect-environment.outputs.action }}"
      -
        name: Setup PHP
        if: steps.inspect-environment.outputs.action != 'none'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: none
          tools: none
          coverage: none
      -
        name: Checkout
        if: steps.inspect-environment.outputs.action != 'none'
        uses: actions/checkout@v4
      -
        name: Update README
        if: steps.inspect-environment.outputs.action != 'none'
        run: ./.github/workflows/update-readme README.md
      -
        name: Check changes
        if: steps.inspect-environment.outputs.action != 'none'
        id: check-changes
        run: |
          if git diff --color=always --exit-code README.md; then
            echo 'No changes'
          else
            echo 'commit=yes' >>"$GITHUB_OUTPUT"
          fi
      -
        name: Commit
        if: steps.inspect-environment.outputs.action == 'publish' && steps.check-changes.outputs.commit == 'yes'
        run: |
          git add README.md
          git config user.name GitHub
          git config user.email noreply@github.com
          git commit -m 'Update po from Transifex'
          git push
