alias ll='ls -l --all --classify --color=auto'

_ccm_service() {
    case $COMP_CWORD in
        1)
            COMPREPLY=( $(compgen -W 'start restart stop' -- "${COMP_WORDS[COMP_CWORD]}") )
            ;;
        2)
            COMPREPLY=( $(compgen -W 'db web nginx php-fpm php fpm' -- "${COMP_WORDS[COMP_CWORD]}") )
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}
complete -F _ccm_service ccm-service
