#!/bin/sh

set -o nounset
set -o errexit

cat <<EOT
docker5 images come with the following CLI commands:

- ccm-help: display this help text.

- ccm-service: start/restart/stop services.
  Invoke it without arguments to get some help.

- switch-composer: change the composer version to be used.
  Invoke it without arguments to get some help.

- switch-php: change the PHP version to be used.
  Invoke it without arguments to get some help.

EOT
