#!/bin/sh
set -o nounset
set -o errexit

script_name=$0

installedVersions="$(update-alternatives --list php | sed -E 's/\/usr\/bin\/php([0-9]+\.[0-9]+)$/\1/' | sort)"

exitWithSyntax() {
    printf 'Syntax: %s <version>\n\nSwitch the currently active PHP version.\nAvailable versions:\n%s\n' "$script_name" "$installedVersions" >&2
    exit 1
}

version=
while :; do
    if test $# -lt 1; then
        break
    fi
    if test "$version" != ''; then
        exitWithSyntax
    fi
    for installedVersion in $installedVersions; do
        if test "$1" = "$installedVersion"; then
            version=$installedVersion
            break
        fi
    done
    if test "$version" = ''; then
        printf 'PHP version not available: %s\nAvailable versions:\n%s\n' "$1" "$installedVersions" >&2
        exit 1
    fi
    shift
done
if test "$version" = ''; then
    exitWithSyntax
fi

if ccm-service status php-fpm >/dev/null; then
    restartPhpFrm=1
    ccm-service stop php-fpm
else
    restartPhpFrm=0
fi

update-alternatives --set php /usr/bin/php$version >/dev/null 2>/dev/null

if test $restartPhpFrm -eq 1; then
    ccm-service start php-fpm
fi
