#!/bin/sh
set -o nounset
set -o errexit

script_name=$0

installedVersions="$(update-alternatives --list composer | sed -E 's/\/usr\/local\/bin\/composer([0-9]+(\.[0-9]+)?)$/\1/' | sort)"

exitWithSyntax() {
    printf 'Syntax: %s <version>\n\nSwitch the currently active Composer version.\nAvailable versions:\n%s\n' "$script_name" "$installedVersions" >&2
    exit 1
}

version=
while :; do
    if test $# -lt 1; then
        break
    fi
    if test "$version" != ''; then
        exitWithSyntax
    fi
    for installedVersion in $installedVersions; do
        if test "$1" = "$installedVersion"; then
            version=$installedVersion
            break
        fi
    done
    if test "$version" = ''; then
        printf 'Composer version not available: %s\nAvailable versions:\n%s\n' "$1" "$installedVersions" >&2
        exit 1
    fi
    shift
done
if test "$version" = ''; then
    exitWithSyntax
fi

update-alternatives --set composer /usr/local/bin/composer$version >/dev/null 2>/dev/null
